### PR TITLE
refactor: replace throttle for queue

### PR DESCRIPTION
**Pull request by gunar**
Please review and let me know so I can deploy a new version of the extension.

### CODE REVIEW

**Comment by keenahn** [comment]
Nice! This works well. I had a few comments:

1. I changed concurrency to 1 because I was still getting "Too many requests" errors from Slack when I was rapidly deleting with concurrency 2 or 3.
2. I don't want to check in the promise-queue library, but I understand this will be handled in the future with npm and buildpack, so it's fine for now.

**Comment by keenahn** [comment]
Oh yeah, and any reason why we're on version 5 now? Shouldn't we preserve version numbers? I guess it's just a philosophical difference. But that's how we end up with shit like this: Facebook's app is on version 125 http://www.apkmirror.com/apk/facebook-2/facebook/facebook-125-0-0-0-39-release/

**Comment by keenahn** [comment]
And on a meta note, I have copied the labels over from `taut`. I have a script that does this, so I can share that with you guys in next week's meeting.

**Comment by gunar** [comment]
I agree with all your points.
The reason for my doing so is because this extension and repo shall be merged into Zinc soon.

**Pull request merged**
